### ISSUE TITLE
Lesson 3. Task 6

### ISSUE THREAD

**Issue by milkina** [Nikita080196/Uits#1]
1. Вы везде сделали явное преобразование, оставьте его только там где оно действительно нужно.

**Comment by milkina** [comment]
Не доделали?

**Comment by Nikita080196** [comment]
я переделал еще 3 дня назад,правильно?

**Comment by milkina** [comment]
Вы закомментировали части кода. Если он не нужен, то удалите его.
Но вообще я имела ввиду то что, не везде нужно делать явное преобразование.
Например  в методе convertToShort вы пишите:
  short s1 = (short) b;
При преобразовании из byte в short не нужно явное преобразование. Можно написать так:
 short s1 =  b;
Расскоммментируйте и исправьте.

**Comment by Nikita080196** [comment]
Переделал
