### ISSUE TITLE
Lesson 7. Task 4 Car

### ISSUE THREAD

**Issue by milkina** [Nikita080196/Uits#10]
1. Классы Car, Main неотформатированы.
2. Добавить геттеры, сеттеры классу Car.
3. Класс Engine, Driver - переменные должны иметь модификатор доступа private и иметь  геттеры, сеттеры (according to code convention).

**Comment by Nikita080196** [comment]
Переделал.Добавил сэтеры и гэтеры,только выдает ошибку,хотя все прекрасно запускается,можете пожалуйста посмотреть )

**Comment by milkina** [comment]
1. Вы создали объекты  Driver и Engine, но не добавили их в класс Сar. Поэтому у вас выбрасывается ошибка. Можете сделать это через сеттеры или так как было- через конструктор.
2. Если вы добавляете в класс геттеры и сеттеры, это не означает, что вы не можете воспользоваться конструктором для установки значений переменным класса. Вы убрали конструктор, можно было его оставить.

**Comment by Nikita080196** [comment]
Сделано
