### ISSUE TITLE
Lesson 8. Task 2. Рекурсия

### ISSUE THREAD

**Issue by milkina** [Nikita080196/Uits#11]
Вы пишите:
 if (a > b) {
            if (a == b) {//ЭТО УСЛОВИЕ НИКОГДА НЕ БУДЕТ ВЕРНЫМ. ЭТОТ IF МОЖНО УБРАТЬ
                return Integer.toString(a);
            }
            return a + " " + rec(a - 1, b);
        }

**Comment by Nikita080196** [comment]
Здравствуйте,переделал.Добавил lesson8.task5 длинна и площадь круга.
