### ISSUE TITLE
Lesson 12. Task 3. Палиндром.

### ISSUE THREAD

**Issue by milkina** [Nikita080196/Uits#13]
Я немного подправила задание: 
Предложение состоит из нескольких слов, например: "Если есть хвосты по дз, начните с 1 не сданного задания. 123 324 111 4554". Среди слов, состоящих только из цифр, найти слово-палиндром.

То  есть задайте строку, которую разделите на слова и каждое слово проверяйте. 
Можете делать без сканера. Например так: String str ="Если есть хвосты по дз, начните с 1 не сданного задания. 123 324 111 4554".

**Comment by Nikita080196** [comment]
Исправил.Так же сделал несколько тасков.Посмотрите,пожалуйста)

**Comment by milkina** [comment]
При чем здесь минимальное значение различных символов?
Это Рома другое таск делал.

**Comment by Nikita080196** [comment]
Исправил

**Comment by Nikita080196** [comment]
Посмотрите пожалуйста еще lesson10.task6 Фруктовая лавка.
