### ISSUE TITLE
Lesson 10. Task 5. Инструмент 

### ISSUE THREAD

**Issue by milkina** [Nikita080196/Uits#14]
1. Guitar, Baraban . Truba - убрать ненужный импорт, пустые строки. 
2. Напишите сеттеры и геттеры для переменных класса.
3. Переопределить в классах методы toString, equals и hashCode.

**Comment by Nikita080196** [comment]
fix

**Comment by milkina** [comment]
Ставлю done, но не убрали пустую строку в Guitar:

    public void play() {
        System.out.println("Играет " + KEY + " Гитараа");

    }
