### ISSUE TITLE
Lesson4_5. Girlyanda

### ISSUE THREAD

**Issue by milkina** [Nikita080196/Uits#22]
1. turnONFirstPos метод.
Можно просто:

 if (res==0){
            System.out.println("Лампочка на первой позиции выключена.");
} else {
            System.out.println("Лампочка на первой позиции включена.");
}

И используйте  фигурные скобки для блока if.

**Comment by Nikita080196** [comment]
fix

**Comment by milkina** [comment]
Ставлю done, но не отформатировано.
