### ISSUE TITLE
Flower

### ISSUE THREAD

**Issue by milkina** [Nikita080196/Uits#34]
Полный текст задания:
Создать класс "Flower", который содержит переменные страна производитель и срок хранения в днях. Создать классы расширяющие класс Flower (для примера, пусть это будут розы, гвоздики, тюльпаны и... что-то на свой вкус). Суперкласс "Flower" должен содержать абстрактный метод определяющий стоимость цветка, этот метод переопределить в классах наследниках.  Собрать 3 букета (используем массив) с определением их стоимости. В букет может входить несколько цветов разного типа. Также подсчитать количество проданных цветов (используем статический метод).

**Comment by Nikita080196** [comment]
у нас же было задание создать просто абстрактный класс,или я ошибаюсь?А это задание у нас было в lesson8.task4.Только вместо стран было название цветов

**Comment by milkina** [comment]
Оно было в таком виде.

**Comment by Nikita080196** [comment]
Исправил,задание находится в lesson8.task4
