### ISSUE TITLE
Lesson4-5. Task 5.  меньшее по модулю

### ISSUE THREAD

**Issue by milkina** [Nikita080196/Uits#4]
Вы используете число float, так можно, но обычно используют числа double для представления вещественных чисел.

При запуске программы 3 раза выводится сообщение:
Число меньшее по модулю : 3.0
Число меньшее по модулю : 3.0
Число меньшее по модулю : 3.0
Должно быть один раз.

**Comment by Nikita080196** [comment]
переделал
