### ISSUE TITLE
Lesson4-5 . Task 7. Average

### ISSUE THREAD

**Issue by milkina** [Nikita080196/Uits#5]
Вещественные числа передаются на вход программы в качестве аргументов.

**Comment by Nikita080196** [comment]
переделал

**Comment by milkina** [comment]
http://www.examclouds.com/java/java-core-russian/argumenti-komandnoy-stroki - почитайте здесь, что такое аргументы ком. строки. Если непонятно, напомните на уроке - обсудим. Покажу как передавать их из IntellijIDEA

**Comment by Nikita080196** [comment]
Доработал.Все получилось
