### ISSUE TITLE
Lesson 6. Task 4. Массив 

### ISSUE THREAD

**Issue by milkina** [Nikita080196/Uits#7]
При запуске выбрасывается ArrayIndexOutOfBoundsException. Исправьте

**Comment by milkina** [comment]
1. Метод ArrayMinMax не соотв. рек. по именованию. Читайте здесь -http://www.examclouds.com/java/java-core-russian/recomendacii-imenovanie-identificators.
2. У вас везде минимальное значение равно 0, но ваш массив не содержит 0. Для максимума сейчас ищет верно, но если вы подставите отрицательные значения, максимум тоже будет равен 0.  Исправьте.

**Comment by Nikita080196** [comment]
переделал,но проблема в том что когда нет отрицательных значений,то минимум всегда будет 0,но если есть хотя бы одно отрицательное значение,то все работает как нужно.

**Comment by milkina** [comment]
Переменным min and max присваивайте не 0, а первое значение из строки массива

**Comment by Nikita080196** [comment]
Доработал.Сейчас все корректно.Добавил также задание из 7 урока 4 таск про автомобильСпасибо)
