### ISSUE TITLE
Lesson 7. Task 3. Пользователь библиотеки

### ISSUE THREAD

**Issue by milkina** [Nikita080196/Uits#9]
1. Название класса Book, не подходит - у  нас пользователь библиотеки. Назовите, например, LibraryUser.
2. Убрать из конструктора сканнер. Конструктор должен только принимать значения.
3. Методы takebook,  returnbook не соответствуют рекомендациям по именованию.
4. Классы не отформатированы.

**Comment by Nikita080196** [comment]
переделал через гэтэры и сэтеры
